### ISSUE TITLE
Incorrect Calculation of Investment Income for Different Currency

### ISSUE THREAD

**Issue by Zemtrix1** [afadil/wealthfolio#135]
There is an issue in the calculation of investment income when dividends are disbursed in a currency that differs from the General currency. Specifically, when a dividend is paid in USD while the general currency is set to CZK, the dividend amount is presented in USD without being converted to CZK. Consequently, the Investment income reflects a mixture of currencies. In my case, this results in a straightforward subtraction of the CZK and USD values, without considering that USD represents a different currency.

![obrazek](https://github.com/user-attachments/assets/bdd2de22-c29f-4c46-866d-362fe957c9e3)
Expected result in Investment income is 17.85 x 23.1 = 412.335 not just the 17.85

App version: v1.0.18
General currency: CZK

**Comment by wellmoonloft** [comment]
I have the same problem, so I post it here.
I set my base currency to CNY, and  I have some USD stocks and some EUR investments.
When the EUR investment generates income, it is marked as CNY in my investment income, but the amount is still in EUR, without conversion.
I use v1.0.18
<img width="892" alt="image" src="https://github.com/user-attachments/assets/bbc6e347-a487-4aed-ba92-a8b952c5c9f9">

**Comment by wellmoonloft** [comment]
You can test it like this
1. Set the base currency to CNY
2. Open a USD investment account, such as Interactive Brokers
3. Buy the stock 1332.T (Japanese Yen) in the USD investment account
4. You will find the problem
Expand it
5. You can open a EUR account
6. Then deposit funds into the EUR account
7. Then add interest to the EUR account
Then you will find the error in the investment income, because the base currency is CNY, it should be converted into CNY in the investment income. But it only uses the CNY currency symbol, and the amount is still in Euro or US dollars
![image](https://github.com/user-attachments/assets/b9189a0d-1b6f-40a1-bb3e-f3e3ce5f7ae0)

**Comment by maelp** [comment]
Might be linked to https://github.com/afadil/wealthfolio/issues/106 ?

**Comment by afadil** [comment]
Fixed in [v1.0.19](https://github.com/afadil/wealthfolio/releases/tag/v1.0.19)

**Comment by maelp** [comment]
I still have the bug from #106 though

**Comment by mZbZ** [comment]
> I still have the bug from #106 though

I had a similar issue with currency conversion before, deleting and then re-importing the data seems to have fixed these issues. Everything seems to be working now :partying_face:  @afadil

**Comment by maelp** [comment]
Ah I might try that, can you export the current data and then reimport them?

**Comment by maelp** [comment]
Indeed, I confirm that deleting and re-adding fixes the issue, so it might have been an old bug

**Comment by Zemtrix1** [comment]
I also cofirm that the reported issue is fixed with latest version of app! Thx !!
