### ISSUE TITLE
[Feature Request]: Account contribution manager

### ISSUE THREAD

**Issue by colemvnio** [afadil/wealthfolio#136]
In certain countries, yearly contributions per account type must be maintained to prevent tax penalties such as the TFSA in Canada and many more.

Adding a feature to keep track of our contributions could help us prevent such penalties, as the reporting done by the CRA is delayed and we must manually keep track of them. These contributions are seen as `deposits`, and some people often only want to track them and not the actual usage/assets of them.

Having a way to keep track of deposits through your existing deposits, regardless of your assets could be interesting. For example, I personally have an Excel table that says how much I can contribute for 2024, and then I show how much (% and $) is free based on the deposits I did. This is done totally outside of my assets or equities, but ultimately is related.

Thank you,

**Comment by kennydrobnack** [comment]
I'm guessing this is a thing for most any country that has tax-advantaged retirement or savings accounts. In the USA, this is a thing for 401k, Roth IRA, and HSA accounts and others too.

It does vary per year because the IRS adjusts the limits, plus once you reach a certain age, the limits are increased for some accounts.

Two ideas:

Easy implementation: just show how much was contributed to each account per year.

More complicated: allow setting the limit per year and keep track of the contributions vs. limits per year.

**Comment by afadil** [comment]
Added [v1.0.19](https://github.com/afadil/wealthfolio/releases/tag/v1.0.19)
