### ISSUE TITLE
Return the Original CSV Import functionality as a separate option

### ISSUE THREAD

**Issue by evilspades14** [afadil/wealthfolio#162]
I had gotten into a solid workflow of automating CSV imports from various brokerages by creating Python scripts to clean the data, but now those imports fail. In my attempts to use the new importer, I have not been able to complete an import before getting an error that erases my progress. I would much prefer to have the option to create the correct CSV myself and upload it directly as it worked before the most recent update.

**Comment by afadil** [comment]
Could you please share some details of the issue you have with the new import? The standard format should work like before.

**Comment by jeromecornet** [comment]
Running into the same issue, it's a javascript error due to an incorrect CSV parsing. There seems to be a leftover empty row last (despite my CSV not containing any empty line)
For some reason, adding `skipEmptyLines: true` to the Papa parser call works, despite my original CSV not containing any empty lines, but I think it's safe to add this by default

**Comment by jeromecornet** [comment]
I pushed a PR in https://github.com/afadil/wealthfolio/pull/164 with the fix and an example to reproduce the bug
